version: '3.3'
services:
  java-maven-app:
    image: ${IMAGE_NAME} #nelobaba/demo-app:1.1.1-21
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5342:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd